name: "Pull Request Docs Check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs-sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build-Docs
      run: cd docs && ./build_locally.sh
